/**
 * File: comandi.js
 * Descrizione: Contiene tutti i comandi disponibili per il chatbot per modificare il calendario,
 *             dieta, routine e gestione delle ferie.
 * 
 * Questo file viene usato dal chatbot per eseguire le modifiche richieste dall'utente.
 * Ogni funzione restituisce un oggetto con:
 * - successo: boolean (true/false)
 * - messaggio: string (descrizione del risultato)
 * - dati: object (dati modificati o generati)
 * - refresh: boolean (se e' necessario ricaricare la pagina)
 */

/**
 * Salva i dati modificati in localStorage
 */
function salvaDati(chiave, dati) {
    try {
        localStorage.setItem(chiave, JSON.stringify(dati))
        return true
    } catch (e) {
        console.error(`[comandi.js] Errore salvataggio ${chiave}:`, e)
        return false
    }
}
/**
 * Carica i dati da localStorage
 */
function caricaDati(chiave, defaultValue = null) {
    try {
        const dati = localStorage.getItem(chiave)
        return dati ? JSON.parse(dati) : defaultValue
    } catch (e) {
        console.error(`[comandi.js] Errore caricamento ${chiave}:`, e)
        return defaultValue
    }
}

// ============================================
// COMANDI FERIE
// ============================================

/**
 * Aggiunge un periodo di ferie
 * @param {string} startDate - Data inizio nel formato YYYY-MM-DD
 * @param {string} endDate - Data fine nel formato YYYY-MM-DD
 * @returns {object} Risultato dell'operazione
 */
export function aggiungiFerie(startDate, endDate) {
    try {
        // Validazione date
        if (!startDate || !endDate) {
            return {
                successo: false,
                messaggio: "Le date di inizio e fine ferie sono obbligatorie",
                dati: null,
                refresh: false
            }
        }

        const start = new Date(startDate)
        const end = new Date(endDate)

        if (start > end) {
            return {
                successo: false,
                messaggio: "La data di inizio deve essere prima della data di fine",
                dati: null,
                refresh: false
            }
        }

        // Carica ferie esistenti
        let existingVacation = caricaDati('palestra_vacation', { vacationPeriods: [], vacationSuggestions: {} })

        // Assicurati che la struttura sia valida
        if (!existingVacation || !Array.isArray(existingVacation.vacationPeriods)) {
            existingVacation = { vacationPeriods: [], vacationSuggestions: {} }
        }

        // Crea nuovo periodo di ferie
        const newVacationPeriod = {
            id: `vac-${Date.now()}`,
            startDate,
            endDate,
            confirmed: true,
            autoGenerated: false
        }

        // Aggiungi il nuovo periodo
        const updatedVacation = {
            vacationPeriods: [...existingVacation.vacationPeriods, newVacationPeriod],
            vacationSuggestions: generazioneSuggerimentiVacanza(startDate, endDate)
        }

        // Salva
        if (salvaDati('palestra_vacation', updatedVacation)) {
            return {
                successo: true,
                messaggio: `Ferie aggiunte: dal ${startDate} al ${endDate}`,
                dati: updatedVacation,
                refresh: true
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio delle ferie",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nell'aggiunta delle ferie: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Rimuove un periodo di ferie
 * @param {string} vacationId - ID del periodo di ferie da rimuovere
 * @returns {object} Risultato dell'operazione
 */
export function rimuoviFerie(vacationId) {
    try {
        let existingVacation = caricaDati('palestra_vacation', { vacationPeriods: [], vacationSuggestions: {} })

        if (!existingVacation || !Array.isArray(existingVacation.vacationPeriods)) {
            existingVacation = { vacationPeriods: [], vacationSuggestions: {} }
        }

        const updatedVacation = {
            vacationPeriods: existingVacation.vacationPeriods.filter(v => v.id !== vacationId),
            vacationSuggestions: existingVacation.vacationSuggestions
        }

        if (salvaDati('palestra_vacation', updatedVacation)) {
            return {
                successo: true,
                messaggio: `Ferie con ID ${vacationId} rimosse`,
                dati: updatedVacation,
                refresh: true
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella rimozione delle ferie: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Genera suggerimenti per il periodo di vacanza
 * @param {string} startDate - Data inizio
 * @param {string} endDate - Data fine
 * @returns {object} Suggerimenti generati
 */
function generazioneSuggerimentiVacanza(startDate, endDate) {
    const suggestions = {}
    const start = new Date(startDate)
    const end = new Date(endDate)

    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
        const dateStr = d.toISOString().split('T')[0]
        suggestions[dateStr] = {
            workout: {
                type: 'light',
                name: 'Attivita leggera',
                exercises: [
                    'Camminata 30-45 minuti',
                    'Stretching 10 minuti',
                    'Nuoto o bicicletta',
                    'Yoga 15 minuti'
                ],
                tips: 'Mantieni il movimento senza stress'
            },
            diet: {
                type: 'flexible',
                tips: '60% proteine/verdure, 30% carboidrati, 10% dolci',
                baseCalories: 1800
            }
        }
    }
    return suggestions
}

// ============================================
// COMANDI PASTI E ATTIVITA
// ============================================

/**
 * Registra un pasto mangiato (cheat meal)
 * @param {string} description - Descrizione del pasto
 * @param {string} date - Data nel formato YYYY-MM-DD (opzionale, default oggi)
 * @param {number} calories - Calorie (opzionale)
 * @returns {object} Risultato dell'operazione
 */
export function registraPasto(description, date = null, calories = null) {
    try {
        if (!description || !description.trim()) {
            return {
                successo: false,
                messaggio: "La descrizione del pasto e' obbligatoria",
                dati: null,
                refresh: false
            }
        }

        const today = new Date()
        const mealDate = date || today.toISOString().split('T')[0]

        const meal = {
            id: `meal-${Date.now()}`,
            date: mealDate,
            description: description.trim(),
            isCheatMeal: true,
            calories: calories || null,
            done: true
        }

        const activities = caricaDati('palestra_vacation_activities', [])
        const updatedActivities = [...activities, meal]

        if (salvaDati('palestra_vacation_activities', updatedActivities)) {
            return {
                successo: true,
                messaggio: `Pasto registrato: "${description.trim()}"${calories ? ` (${calories} kcal)` : ''}`,
                dati: { meal, activities: updatedActivities },
                refresh: false
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio del pasto",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella registrazione del pasto: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Registra un'attivita' eseguita
 * @param {string} description - Descrizione dell'attivita'
 * @param {string} date - Data nel formato YYYY-MM-DD (opzionale, default oggi)
 * @param {string} type - Tipo di attivita' (opzionale, default 'workout')
 * @returns {object} Risultato dell'operazione
 */
export function registraAttivita(description, date = null, type = 'workout') {
    try {
        if (!description || !description.trim()) {
            return {
                successo: false,
                messaggio: "La descrizione dell'attivita' e' obbligatoria",
                dati: null,
                refresh: false
            }
        }

        const today = new Date()
        const activityDate = date || today.toISOString().split('T')[0]

        const activity = {
            id: `act-${Date.now()}`,
            date: activityDate,
            type: type || 'workout',
            description: description.trim(),
            done: true
        }

        const activities = caricaDati('palestra_vacation_activities', [])
        const updatedActivities = [...activities, activity]

        if (salvaDati('palestra_vacation_activities', updatedActivities)) {
            return {
                successo: true,
                messaggio: `Attivita' registrata: "${description.trim()}"`,
                dati: { activity, activities: updatedActivities },
                refresh: false
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio dell'attivita'",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella registrazione dell'attivita': ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

// ============================================
// COMANDI PIANO DI RIENTRO
// ============================================

/**
 * Genera un piano di rientro dopo le ferie
 * @param {object} context - Contesto con dati utente e piano corrente
 * @returns {object} Risultato dell'operazione
 */
export function generaPianoRientro(context = null) {
    try {
        const activities = caricaDati('palestra_vacation_activities', [])
        const doneWorkouts = activities.filter(a => a.type === 'workout' && a.done).length
        const cheatMeals = activities.filter(a => a.isCheatMeal).length

        // Determina l'obiettivo dalle preferenze o dal contesto
        let baseCalories = 1800
        let adjustment = -200
        let tips = 'Riduci carboidrati del 15% per compensare gli sgarri'

        if (context && context.data) {
            if (context.data.obiettivo === 'Massa Muscolare') {
                baseCalories = 2200
                tips = 'Aumenta proteine del 20% per recuperare'
            } else if (context.data.obiettivo === 'Dimagrimento') {
                baseCalories = 1600
                adjustment = -300
                tips = 'Riduci carboidrati del 25% per accelerare il dimagrimento'
            }
        }

        const returnPlan = {
            startDate: new Date().toISOString().split('T')[0],
            duration: 7,
            phase: 'recovery',
            workout: {
                intensity: 'gradual',
                schedule: generaProgrammaRientro(doneWorkouts)
            },
            diet: {
                baseCalories,
                adjustment,
                tips
            },
            notes: `Piano basato su ${doneWorkouts} attivita' eseguite e ${cheatMeals} sgarri`
        }

        if (salvaDati('palestra_return_plan', returnPlan)) {
            return {
                successo: true,
                messaggio: "Piano di rientro generato per 7 giorni!",
                dati: returnPlan,
                refresh: false
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio del piano di rientro",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella generazione del piano di rientro: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Genera il programma di rientro basato sul numero di attivita' eseguite
 * @param {number} doneWorkouts - Numero di attivita' eseguite
 * @returns {array} Programma di rientro
 */
function generaProgrammaRientro(doneWorkouts) {
    return [
        { day: 1, type: 'cardio', duration: '30 min', intensity: 'light' },
        { day: 2, type: doneWorkouts < 2 ? 'rest' : 'full-body', description: doneWorkouts < 2 ? 'Recupero' : 'Allenamento completo' },
        { day: 3, type: 'cardio', duration: '35 min', intensity: 'moderate' },
        { day: 4, type: 'upper-body', duration: '45 min', intensity: 'moderate' },
        { day: 5, type: 'rest', description: 'Recupero attivo' },
        { day: 6, type: 'lower-body', duration: '50 min', intensity: 'moderate' },
        { day: 7, type: 'normal', description: 'Ritorno al piano normale' }
    ]
}

// ============================================
// COMANDI MODIFICA CALENDARIO (DIETA E ROUTINE)
// ============================================

/**
 * Modifica la dieta per un giorno specifico
 * @param {string} giorno - Nome del giorno (es. 'Lunedi')
 * @param {object} pasti - Oggetto con i pasti da modificare
 * @returns {object} Risultato dell'operazione
 */
export function modificaDieta(giorno, pasti) {
    try {
        if (!giorno) {
            return {
                successo: false,
                messaggio: "Il giorno e' obbligatorio",
                dati: null,
                refresh: true
            }
        }

        if (!pasti || typeof pasti !== 'object' || Object.keys(pasti).length === 0) {
            return {
                successo: false,
                messaggio: "I pasti da modificare sono obbligatori",
                dati: null,
                refresh: false
            }
        }

        // Carica suggerimenti correnti
        let currentSuggestions = caricaDati('palestra_suggestions', { dieta: {}, routine: {}, calendario: {} })

        if (!currentSuggestions.dieta) {
            currentSuggestions.dieta = {}
        }

        // Applica modifiche (merge)
        const newDieta = { ...currentSuggestions.dieta }
        newDieta[giorno] = {
            ...newDieta[giorno],
            pasti: pasti.pasti ? { ...pasti.pasti } : { ...pasti }
        }

        // Salva
        const updatedSuggestions = {
            ...currentSuggestions,
            dieta: newDieta
        }

        if (salvaDati('palestra_suggestions', updatedSuggestions)) {
            return {
                successo: true,
                messaggio: `Dieta modificata per il ${giorno}`,
                dati: updatedSuggestions,
                refresh: true
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio della dieta",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella modifica della dieta: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Modifica la routine per un giorno specifico
 * @param {string} giorno - Nome del giorno (es. 'Lunedi')
 * @param {object} dati - Dati della routine da modificare
 * @returns {object} Risultato dell'operazione
 */
export function modificaRoutine(giorno, dati) {
    try {
        if (!giorno) {
            return {
                successo: false,
                messaggio: "Il giorno e' obbligatorio",
                dati: null,
                refresh: true
            }
        }

        if (!dati || typeof dati !== 'object' || Object.keys(dati).length === 0) {
            return {
                successo: false,
                messaggio: "I dati della routine sono obbligatori",
                dati: null,
                refresh: false
            }
        }

        // Carica suggerimenti correnti
        let currentSuggestions = caricaDati('palestra_suggestions', { dieta: {}, routine: {}, calendario: {} })

        if (!currentSuggestions.routine) {
            currentSuggestions.routine = {}
        }

        // Applica modifiche (merge)
        const newRoutine = { ...currentSuggestions.routine }
        newRoutine[giorno] = { ...dati }

        // Salva
        const updatedSuggestions = {
            ...currentSuggestions,
            routine: newRoutine
        }

        if (salvaDati('palestra_suggestions', updatedSuggestions)) {
            return {
                successo: true,
                messaggio: `Routine modificata per il ${giorno}`,
                dati: updatedSuggestions,
                refresh: true
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio della routine",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nella modifica della routine: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Applica tutte le modifiche suggerite dal chatbot
 * @param {object} modifiche - Oggetto con dieta e routine da modificare
 * @returns {object} Risultato dell'operazione
 */
export function applicaModifiche(modifiche) {
    try {
        if (!modifiche || typeof modifiche !== 'object' || Object.keys(modifiche).length === 0) {
            return {
                successo: false,
                messaggio: "Nessuna modifica da applicare",
                dati: null,
                refresh: false
            }
        }

        // Carica suggerimenti correnti
        let currentSuggestions = caricaDati('palestra_suggestions', { dieta: {}, routine: {}, calendario: {} })

        // Applica modifiche alla dieta
        const newDieta = { ...currentSuggestions.dieta }
        if (modifiche.dieta && typeof modifiche.dieta === 'object') {
            Object.entries(modifiche.dieta || {}).forEach(([giorno, dati]) => {
                newDieta[giorno] = {
                    ...newDieta[giorno],
                    pasti: dati.pasti ? { ...dati.pasti } : {}
                }
            })
        }

        // Applica modifiche alla routine
        const newRoutine = { ...currentSuggestions.routine }
        if (modifiche.routine && typeof modifiche.routine === 'object') {
            Object.entries(modifiche.routine || {}).forEach(([giorno, dati]) => {
                newRoutine[giorno] = { ...dati }
            })
        }

        // Crea il nuovo oggetto suggerimenti
        const updatedSuggestions = {
            ...currentSuggestions,
            dieta: newDieta,
            routine: newRoutine
        }

        // Salva
        if (salvaDati('palestra_suggestions', updatedSuggestions)) {
            return {
                successo: true,
                messaggio: "Modifiche applicate con successo!",
                dati: updatedSuggestions,
                refresh: true
            }
        } else {
            return {
                successo: false,
                messaggio: "Errore nel salvataggio delle modifiche",
                dati: null,
                refresh: false
            }
        }

    } catch (e) {
        return {
            successo: false,
            messaggio: `Errore nell'applicazione delle modifiche: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Esegue un comando in base al tipo
 * @param {string} tipo - Tipo di comando (ferie, pasto, attivita, rientro, dieta, routine) o comando testuale completo
 * @param {object} parametri - Parametri del comando
 * @returns {object} Risultato dell'operazione
 */
export function eseguiComando(tipo, parametri = {}) {
    try {
        console.log(`[COMANDO] Eseguo: tipo="${tipo}", parametri=`, parametri)

        // Se tipo e' un comando testuale completo (es: "/ferie 15-01 20-01")
        if (typeof tipo === 'string' && tipo.startsWith('/')) {
            // Prova a parsare il comando testuale
            const commandMatch = tipo.match(/^\/(ferie|pasto|mangiato|attivita|fatto|rientro|dieta|routine|modifiche|aggiungi[-_]?ferie|aggiorna[-_]?piano)\s*(.*)?$/i)
            if (commandMatch) {
                const cmdType = commandMatch[1].toLowerCase().replace(/[_-]/g, '')
                const cmdArgs = commandMatch[2] ? commandMatch[2].trim() : ''

                console.log(`[COMANDO] Parsing testuale: cmdType="${cmdType}", cmdArgs="${cmdArgs}"`)

                // Parsa i parametri dal comando testuale
                let parsedParametri = {}

                switch (cmdType) {
                    case 'ferie':
                    case 'aggiuniferie':
                    case 'aggiungiferie':
                        // Formato: /ferie 15-01 20-01
                        const dates = cmdArgs.split(/\s+/).filter(Boolean)
                        if (dates.length >= 2) {
                            parsedParametri = { startDate: dates[0], endDate: dates[1] }
                            console.log(`[COMANDO] Ferie parsed: startDate="${parsedParametri.startDate}", endDate="${parsedParametri.endDate}"`)
                        } else {
                            console.warn(`[COMANDO] Formato date non valido per ferie: "${cmdArgs}"`)
                            return {
                                successo: false,
                                messaggio: `Formato date non valido. Usa: /ferie GG-MM GG-MM (es: /ferie 15-01 20-01)`,
                                dati: null,
                                refresh: false
                            }
                        }
                        return aggiungiFerie(parsedParametri.startDate, parsedParametri.endDate)

                    case 'pasto':
                    case 'mangiato':
                        parsedParametri = { description: cmdArgs || tipo }
                        console.log(`[COMANDO] Pasto: description="${parsedParametri.description}"`)
                        return registraPasto(parsedParametri.description)

                    case 'attivita':
                    case 'fatto':
                        parsedParametri = { description: cmdArgs || tipo }
                        console.log(`[COMANDO] Attivita: description="${parsedParametri.description}"`)
                        return registraAttivita(parsedParametri.description)

                    case 'rientro':
                    case 'aggiornapiano':
                        console.log(`[COMANDO] Rientro: generando piano di rientro`)
                        return generaPianoRientro(null)

                    default:
                        console.warn(`[COMANDO] Comando testuale non supportato: ${tipo}`)
                        return {
                            successo: false,
                            messaggio: `Comando testuale non supportato: ${tipo}`,
                            dati: null,
                            refresh: false
                        }
                }
            }
        }

        // Comando come oggetto (tipo + parametri separati)
        console.log(`[COMANDO] Switch: tipo="${tipo.toLowerCase()}"`)
        
        // Normalizza il tipo di comando: rimuovi underscore, trattini e converti in minuscolo
        const tipoNormalizzato = tipo.toLowerCase().replace(/[_-]/g, '')
        console.log(`[COMANDO] Normalizzato: tipoNormalizzato="${tipoNormalizzato}"`)
        
        switch (tipoNormalizzato) {
            case 'ferie':
            case 'aggiuniferie':
            case 'aggiungiferie':
                console.log(`[COMANDO] Ferie: startDate="${parametri.startDate}", endDate="${parametri.endDate}"`)
                return aggiungiFerie(parametri.startDate, parametri.endDate)
            case 'pasto':
            case 'mangiato':
                console.log(`[COMANDO] Pasto: description="${parametri.description}", date="${parametri.date}", calories="${parametri.calories}"`)
                return registraPasto(parametri.description, parametri.date, parametri.calories)
            case 'attivita':
            case 'fatto':
                console.log(`[COMANDO] Attivita: description="${parametri.description}", type="${parametri.type}"`)
                return registraAttivita(parametri.description, parametri.date, parametri.type)
            case 'rientro':
            case 'piano rientro':
            case 'aggiornapiano':
                console.log(`[COMANDO] Rientro: context=`, parametri?.context)
                return generaPianoRientro(parametri?.context || null)
            case 'dieta':
                console.log(`[COMANDO] Dieta: giorno="${parametri.giorno}", pasti=`, parametri.pasti)
                return modificaDieta(parametri.giorno, parametri.pasti)
            case 'routine':
                console.log(`[COMANDO] Routine: giorno="${parametri.giorno}", dati=`, parametri.dati)
                return modificaRoutine(parametri.giorno, parametri.dati)
            case 'modifiche':
                console.log(`[COMANDO] Modifiche: modifiche=`, parametri.modifiche)
                return applicaModifiche(parametri.modifiche)
            default:
                console.warn(`[COMANDO] Comando sconosciuto: ${tipo} (normalizzato: ${tipoNormalizzato})`)
                return {
                    successo: false,
                    messaggio: `Comando sconosciuto: ${tipo}. Comandi validi: ferie, pasto, attivita, rientro, dieta, routine, modifiche`,
                    dati: null,
                    refresh: false
                }
        }
    } catch (e) {
        console.error(`[COMANDO] Errore in eseguiComando:`, e)
        return {
            successo: false,
            messaggio: `Errore nell'esecuzione del comando: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}

/**
 * Esegue piu' comandi in sequenza
 * @param {array} comandi - Array di comandi da eseguire [{ tipo, parametri }] o array di stringhe
 * @returns {object} Risultato dell'operazione
 */
export function eseguiComandi(comandi = []) {
    try {
        if (!Array.isArray(comandi) || comandi.length === 0) {
            return {
                successo: false,
                messaggio: "Nessun comando da eseguire",
                dati: null,
                refresh: false
            }
        }

        const risultati = []
        let necessitaRefresh = false
        let erroriDettagliati = []

        for (let i = 0; i < comandi.length; i++) {
            const comando = comandi[i]

            // Supporta sia oggetti {tipo, parametri} che stringhe dirette
            let tipo, parametri

            if (typeof comando === 'string') {
                // Comando come stringa (es: "/ferie 15-01 20-01")
                tipo = comando
                parametri = {}
            } else if (comando && typeof comando === 'object') {
                tipo = comando.tipo
                parametri = comando.parametri || {}
            } else {
                const errMsg = `Comando ${i + 1}/${comandi.length} non valido: tipo = ${typeof comando}`
                erroriDettagliati.push(errMsg)
                risultati.push({
                    successo: false,
                    messaggio: errMsg,
                    dati: null,
                    refresh: false
                })
                continue
            }

            console.log(`[COMANDI] Eseguo comando ${i + 1}/${comandi.length}: tipo="${tipo}", parametri=`, parametri)

            const risultato = eseguiComando(tipo, parametri)
            risultati.push(risultato)

            if (risultato.refresh) {
                necessitaRefresh = true
            }

            if (!risultato.successo) {
                erroriDettagliati.push(`Comando ${i + 1} (${tipo}): ${risultato.messaggio}`)
            }
        }

        // Verifica se tutti i comandi sono andati a buon fine
        const tuttiSuccesso = risultati.every(r => r.successo)

        const messaggio = tuttiSuccesso
            ? `Tutti i ${comandi.length} comandi eseguiti con successo`
            : `${risultati.filter(r => r.successo).length}/${comandi.length} comandi eseguiti. Errori: ${erroriDettagliati.join('; ')}`

        console.log(`[COMANDI] Risultato: ${messaggio}`)

        return {
            successo: tuttiSuccesso,
            messaggio: messaggio,
            dati: { risultati, erroriDettagliati },
            refresh: necessitaRefresh
        }

    } catch (e) {
        console.error('[COMANDI] Errore critico in eseguiComandi:', e)
        return {
            successo: false,
            messaggio: `Errore critico: ${e.message}`,
            dati: null,
            refresh: false
        }
    }
}
