import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

export default function Vacations() {
    const navigate = useNavigate()
    
    const [vacationData, setVacationData] = useState({
        vacationPeriods: [],
        vacationSuggestions: {}
    })
    const [newVacation, setNewVacation] = useState({
        startDate: '',
        endDate: ''
    })
    const [error, setError] = useState('')
    const [success, setSuccess] = useState('')
    const [generatingPlan, setGeneratingPlan] = useState(false)
    const [returnPlan, setReturnPlan] = useState(null)

    // Carica dati al montaggio (parse sicuro + live update via evento + piano rientro)
    useEffect(() => {
        const loadVacation = () => {
            const savedVacation = localStorage.getItem('palestra_vacation')
            if (savedVacation) {
                try {
                    setVacationData(JSON.parse(savedVacation))
                } catch {
                    setVacationData({ vacationPeriods: [], vacationSuggestions: {} })
                }
            }
            // NOTA 2026-09-05: piano rientro mai mostrato prima, ora visibile
            const savedReturn = localStorage.getItem('palestra_return_plan')
            if (savedReturn) {
                try {
                    setReturnPlan(JSON.parse(savedReturn))
                } catch {
                    setReturnPlan(null)
                }
            } else {
                setReturnPlan(null)
            }
        }
        loadVacation()
        const onUpdate = () => loadVacation()
        window.addEventListener('palestra_data_updated', onUpdate)
        window.addEventListener('storage', onUpdate)
        return () => {
            window.removeEventListener('palestra_data_updated', onUpdate)
            window.removeEventListener('storage', onUpdate)
        }
    }, [])

    // Gestione nuovi periodi ferie
    const handleVacationInputChange = (e) => {
        const { name, value } = e.target
        setNewVacation(prev => ({ ...prev, [name]: value }))
    }

    const addVacationPeriod = () => {
        if (!newVacation.startDate || !newVacation.endDate) {
            setError('Inserisci sia la data di inizio che di fine')
            return
        }
        
        if (new Date(newVacation.startDate) > new Date(newVacation.endDate)) {
            setError('La data di inizio deve essere prima della data di fine')
            return
        }
        
        const newPeriod = {
            id: `vac-${Date.now()}`,
            startDate: newVacation.startDate,
            endDate: newVacation.endDate,
            confirmed: true,
            autoGenerated: false
        }
        
        const updatedVacationData = {
            ...vacationData,
            vacationPeriods: [...vacationData.vacationPeriods, newPeriod]
        }
        
        setVacationData(updatedVacationData)

        // Salva in localStorage + avvisa calendario senza reload
        try {
            localStorage.setItem('palestra_vacation', JSON.stringify(updatedVacationData))
            window.dispatchEvent(new Event('palestra_data_updated'))
        } catch (e) {
            console.error('Errore salvataggio ferie:', e)
            setError('Errore nel salvataggio delle ferie')
        }

        setNewVacation({ startDate: '', endDate: '' })
        setError('')
        setSuccess('Periodo di ferie aggiunto!')
    }

    const removeVacationPeriod = (id) => {
        const updatedVacationData = {
            ...vacationData,
            vacationPeriods: vacationData.vacationPeriods.filter(p => p.id !== id)
        }
        
        setVacationData(updatedVacationData)

        // Salva in localStorage + avvisa calendario senza reload
        try {
            localStorage.setItem('palestra_vacation', JSON.stringify(updatedVacationData))
            window.dispatchEvent(new Event('palestra_data_updated'))
        } catch (e) {
            console.error('Errore rimozione ferie:', e)
            setError('Errore nella rimozione delle ferie')
        }
    }

    // Genera piano vacanza automaticamente
    const generateVacationPlan = () => {
        if (vacationData.vacationPeriods.length === 0) {
            setError('Aggiungi almeno un periodo di ferie')
            return
        }
        
        setGeneratingPlan(true)
        setError('')
        
        // Simulo generazione automatica (in futuro chiamera' API Mistral)
        setTimeout(() => {
            const newSuggestions = {}
            
            vacationData.vacationPeriods.forEach(period => {
                const start = new Date(period.startDate + 'T12:00:00')
                const end = new Date(period.endDate + 'T12:00:00')

                for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
                    const y = d.getFullYear()
                    const m = String(d.getMonth() + 1).padStart(2, '0')
                    const g = String(d.getDate()).padStart(2, '0')
                    const dateStr = `${y}-${m}-${g}`
                    newSuggestions[dateStr] = {
                        workout: {
                            type: 'light',
                            name: 'Attivit\u00e0 leggera vacanza',
                            exercises: [
                                'Camminata 30-45 minuti al mattino',
                                'Stretching 10 minuti',
                                'Nuoto o bicicletta (opzionale)',
                                'Yoga 15 minuti'
                            ],
                            tips: 'Mantieni il movimento senza stress. Idratati costantemente.'
                        },
                        diet: {
                            type: 'flexible',
                            tips: 'Mantieni equilibrio: 60% proteine/verdure, 30% carboidrati, 10% dolci.',
                            baseCalories: 1800
                        }
                    }
                }
            })
            
            const updatedVacationData = {
                ...vacationData,
                vacationSuggestions: newSuggestions
            }
            
            setVacationData(updatedVacationData)

            // Salva in localStorage + avvisa calendario senza reload
            try {
                localStorage.setItem('palestra_vacation', JSON.stringify(updatedVacationData))
                window.dispatchEvent(new Event('palestra_data_updated'))
            } catch (e) {
                console.error('Errore salvataggio piano vacanza:', e)
                setError('Errore nel salvataggio del piano vacanza')
            }
            
            setGeneratingPlan(false)
            setSuccess('Piano vacanza generato automaticamente!')
        }, 1000)
    }

    return (
        <div className="container py-4">
            {/* Header */}
            <div className="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h1 className="mb-1 d-flex align-items-center gap-2">
                        <i className="bi bi-airplane text-warning"></i>
                        Gestione Ferie
                    </h1>
                    <p className="text-muted mb-0">Aggiungi e gestisci i tuoi periodi di ferie</p>
                </div>
                <button 
                    className="btn btn-outline-primary btn-sm d-flex align-items-center gap-1"
                    onClick={() => navigate('/')}
                >
                    <i className="bi bi-arrow-left"></i> Calendario
                </button>
            </div>

            {/* Alerts */}
            {error && (
                <div className="alert alert-danger alert-dismissible fade show mb-4">
                    <i className="bi bi-exclamation-triangle me-2"></i>
                    {error}
                    <button type="button" className="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            )}

            {success && (
                <div className="alert alert-success alert-dismissible fade show mb-4">
                    <i className="bi bi-check-circle me-2"></i>
                    {success}
                    <button type="button" className="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            )}

            {/* Form per aggiungere nuovo periodo */}
            <div className="card border-0 shadow-sm mb-4">
                <div className="card-header bg-light">
                    <h5 className="mb-0 d-flex align-items-center gap-2">
                        <i className="bi bi-calendar-plus"></i> Aggiungi Nuovo Periodo di Ferie
                    </h5>
                </div>
                <div className="card-body">
                    <p className="text-muted small mb-3">
                        Inserisci le date di inizio e fine del periodo di ferie. L'IA generer\u00e0 automaticamente un piano adattato con esercizi leggeri e una dieta flessibile.
                    </p>
                    
                    <div className="row g-3 mb-4">
                        <div className="col-md-5">
                            <label className="form-label">
                                <i className="bi bi-calendar-plus me-1"></i> Data Inizio
                            </label>
                            <input
                                type="date"
                                className="form-control"
                                name="startDate"
                                value={newVacation.startDate}
                                onChange={handleVacationInputChange}
                                required
                            />
                        </div>
                        <div className="col-md-5">
                            <label className="form-label">
                                <i className="bi bi-calendar-minus me-1"></i> Data Fine
                            </label>
                            <input
                                type="date"
                                className="form-control"
                                name="endDate"
                                value={newVacation.endDate}
                                onChange={handleVacationInputChange}
                                min={newVacation.startDate}
                                required
                            />
                        </div>
                        <div className="col-md-2 d-flex align-items-end">
                            <button
                                className="btn btn-primary w-100"
                                onClick={addVacationPeriod}
                                disabled={!newVacation.startDate || !newVacation.endDate}
                                title="Aggiungi periodo ferie"
                            >
                                <i className="bi bi-plus-lg"></i>
                            </button>
                        </div>
                    </div>

                    {/* Genera piano vacanza */}
                    {vacationData.vacationPeriods.length > 0 && (
                        <div className="d-flex gap-2 mb-4">
                            <button
                                className="btn btn-success btn-sm d-flex align-items-center gap-1"
                                onClick={generateVacationPlan}
                                disabled={generatingPlan}
                            >
                                {generatingPlan ? (
                                    <>
                                        <span className="spinner-border spinner-border-sm" role="status"></span>
                                        Generazione...
                                    </>
                                ) : (
                                    <>
                                        <i className="bi bi-robot"></i> Genera Piano Vacanza
                                    </>
                                )}
                            </button>
                        </div>
                    )}

                    {/* Lista periodi ferie salvati */}
                    {vacationData.vacationPeriods.length > 0 && (
                        <div className="mb-3">
                            <h6 className="mb-2">Periodi di Ferie Salvati:</h6>
                            <div className="list-group list-group-flush">
                                {vacationData.vacationPeriods.map(period => (
                                    <div 
                                        key={period.id}
                                        className="list-group-item d-flex justify-content-between align-items-center"
                                    >
                                        <div>
                                            <strong>{new Date(period.startDate + 'T12:00:00').toLocaleDateString('it-IT')}</strong>
                                            {' -> '}
                                            <strong>{new Date(period.endDate + 'T12:00:00').toLocaleDateString('it-IT')}</strong>
                                            {period.autoGenerated && (
                                                <span className="badge bg-info ms-2">Auto</span>
                                            )}
                                        </div>
                                        <button
                                            className="btn btn-sm btn-outline-danger"
                                            onClick={() => removeVacationPeriod(period.id)}
                                            title="Rimuovi"
                                        >
                                            <i className="bi bi-trash"></i>
                                        </button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Info piano vacanza */}
                    {vacationData.vacationPeriods.length > 0 && Object.keys(vacationData.vacationSuggestions).length > 0 && (
                        <div className="alert alert-info">
                            <i className="bi bi-check-circle me-2"></i>
                            Piano vacanza generato! Gli esercizi consigliati sono facoltativi. Puoi segnarli come eseguiti nel calendario.
                        </div>
                    )}
                    {/* Piano rientro generato via chat: prima mai mostrato */}
                    {returnPlan && (
                        <div className="card border-0 shadow-sm mt-3">
                            <div className="card-body">
                                <h6 className="mb-2">Piano di rientro (7 giorni)</h6>
                                <div className="small text-muted mb-2">
                                    Dal {returnPlan.startDate} — {returnPlan.notes || ''}
                                </div>
                                <div className="small mb-2">
                                    Calorie base: {returnPlan.diet?.baseCalories} ({returnPlan.diet?.adjustment} kcal) — {returnPlan.diet?.tips}
                                </div>
                                <ul className="small mb-0 ps-3">
                                    {(returnPlan.workout?.schedule || []).map((s, idx) => (
                                        <li key={idx}>Giorno {s.day}: {s.type}{s.duration ? ` ${s.duration}` : ''}{s.description ? ` — ${s.description}` : ''}</li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Pulsante di navigazione a impostazioni */}
            <div className="card border-0 shadow-sm mt-4">
                <div className="card-body text-center">
                    <button 
                        className="btn btn-outline-secondary btn-lg px-5 d-flex align-items-center gap-2 mx-auto"
                        onClick={() => navigate('/settings')}
                    >
                        <i className="bi bi-gear"></i> Vai alle Impostazioni
                    </button>
                </div>
            </div>
        </div>
    )
}
